### ISSUE TITLE
Hitboxes aren't changed

### ISSUE THREAD

**Issue by NPC-Master3304** [ryanbester/shfa#2]
https://user-images.githubusercontent.com/71358236/214896423-bbd8e5ce-b888-472f-bf27-0e326d879fbe.mp4
┐('～`；)┌

**Comment by ryanbester** [comment]
Are you pressing the key to toggle the mod on (default is h I believe)?

**Comment by NPC-Master3304** [comment]
oh im so stupid (－‸ლ)
