### ISSUE TITLE
[Request] Torch Hitbox Compatibility?

### ISSUE THREAD

**Issue by NPC-Master3304** [ryanbester/shfa#3]
Torches don't extend their hitbox, so I'd figure I'd make this as a request for any future updates. ┐('～`；)┌

**Comment by ryanbester** [comment]
I'll work on adding torches now. Since certain blocks are coded differently in Minecraft, some blocks won't work out of the box. Just open an issue if that's the case and I'll add support for them :)

**Comment by NPC-Master3304** [comment]
oh rlly? wow. well alrighty then haha. i honestly wasnt expecting u 2 do it now since i didnt want 2 force u or smth.

**Comment by ryanbester** [comment]
I have just released version 1.0.3, which includes support for torches, end rods, carpet, and lanterns.

Note that you will have to add them to your SHFA settings, or delete `config/shfa.json`.

**Comment by NPC-Master3304** [comment]
o alrighty. thank u so muchhh <3
